twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        invite_from_address: '%env(INVITE_FROM_ADDRESS)%'
        calDAVEnabled: '%env(CALDAV_ENABLED)%'
        cardDAVEnabled: '%env(CARDDAV_ENABLED)%'
        authRealm: '%env(AUTH_REALM)%'