version: "3.7"

services:

  nginx:
    image: nginx:1.17.5-alpine
    container_name: nginx
    env_file: .env
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - davis
    volumes:
      - davis_www:/var/www/davis
      - type: bind
        source: ./configurations/davis.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  mysql:
    image: mariadb:10.4.10
    container_name: mysql
    env_file: .env

  davis:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        version: "1.4.5"
    image: davis:1.4.5
    container_name: davis
    env_file: .env
    depends_on:
      - mysql
    volumes:
      - davis_www:/var/www/davis

volumes:
  davis_www:
    name: davis_www