name: CI

on: ["push", "pull_request"]

env:
    COMPOSER_ALLOW_SUPERUSER: '1'
    SYMFONY_DEPRECATIONS_HELPER: max[self]=0

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        container:
            image: php:8.0-alpine
            options: >-
              --tmpfs /tmp:exec
              --tmpfs /var/tmp:exec
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Composer
              run: wget -qO - https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet
            - name: Cache Composer dependencies
              uses: actions/cache@v1
              with:
                path: ~/.composer/cache
                key: composer-php${{ matrix.php }}-highest-
                restore-keys: |
                   composer-php${{ matrix.php }}-highest-
                   composer-
            - name: Validate Composer
              run: composer validate
            - name: Install highest dependencies with Composer
              run: composer update --no-progress --ansi
            - name: Analyze
              run: vendor/bin/php-cs-fixer fix --ansi

    phpunit:
        name: PHPUnit (PHP ${{ matrix.php }} Deps ${{ matrix.dependencies }})
        runs-on: ubuntu-latest
        container:
            image: php:${{ matrix.php }}-alpine
            options: >-
              --tmpfs /tmp:exec
              --tmpfs /var/tmp:exec
        services:
          postgres:
            image: postgres:14-alpine
            env:
              POSTGRES_PASSWORD: postgres
            options: >-
              --health-cmd pg_isready
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 5432:5432
        strategy:
            matrix:
                php:
                    - '7.3'
                    - '7.4'
                    - '8.0'
                dependencies:
                    - lowest
                    - highest
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install pgsql PHP extension
              run: |
                apk add $PHPIZE_DEPS libpq-dev
                docker-php-ext-install pdo pdo_pgsql
            - name: Install Composer
              run: wget -qO - https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --quiet
            - name: Cache Composer dependencies
              uses: actions/cache@v1
              with:
                path: ~/.composer/cache
                key: composer-php${{ matrix.php }}-${{ matrix.dependencies }}-
                restore-keys: |
                    composer-php${{ matrix.php }}-${{ matrix.dependencies }}-
                    composer-
            - name: Install lowest dependencies with Composer
              if: matrix.dependencies == 'lowest'
              run: composer update --no-progress --prefer-stable --prefer-lowest --ansi
            - name: Install highest dependencies with Composer
              if: matrix.dependencies == 'highest'
              run: composer update --no-progress --ansi
            - name: Run tests with PHPUnit
              run: vendor/bin/phpunit --process-isolation --colors=always
              env:
                ADMIN_LOGIN: admin
                ADMIN_PASSWORD: test
                DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?serverVersion=14
